apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: digital-planner-certificate
  namespace: default
spec:
  dnsNames:
    - digital-planner.ddnsking.com
  secretName: digital-planner-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer