apiVersion: v1
kind: Secret
metadata:
  name: digital-planner-secret
  namespace: default
type: Opaque
data:
  APP_VERSION: {{ .Values.APP_VERSION | b64enc | quote }}
  DB_VERSION: {{ .Values.DB_VERSION | b64enc | quote }}
  DB_PORT_IN: {{ .Values.DB_PORT_IN | b64enc | quote }}
  DB_PORT_OUT: {{ .Values.DB_PORT_OUT | b64enc | quote }}
  ACCEPT_EULA: {{ .Values.ACCEPT_EULA | b64enc | quote }}
  MSSQL_SA_USER: {{ .Values.MSSQL_SA_USER | b64enc | quote }}
  MSSQL_PID: {{ .Values.MSSQL_PID | b64enc }}
  MSSQL_AGENT_ENABLED: {{ .Values.MSSQL_AGENT_ENABLED | b64enc | quote }}
  DATA_VOLUME: {{ .Values.DATA_VOLUME | b64enc }}
  MSSQL_SERVER: {{ .Values.MSSQL_SERVER | b64enc }}
  DRIVER: {{ .Values.DRIVER | b64enc }}
  PROTOCOL: {{ .Values.PROTOCOL | b64enc }}
  OPTIONS: {{ .Values.OPTIONS | b64enc | quote}}