apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digital-planner-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: digital-planner-secret-store

  target:
    name: digital-planner-external-secret
    creationPolicy: Owner

  data:
  - secretKey: MSSQL_DB
    remoteRef:
      key: MSSQL-DB

  - secretKey: MSSQL_SA_PASSWORD
    remoteRef:
      key: MSSQL-SA-PASSWORD

  - secretKey: MSSQL_USER
    remoteRef:
      key: MSSQL-USER

  - secretKey: MSSQL_PASSWORD
    remoteRef:
      key: MSSQL-PASSWORD