apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-monitoring
  namespace: default
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: charts/kube-monitoring
    repoURL: git@github.com:adam-stegienko/Portfolio-Configuration.git
    # targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true